<!--
Copyright (C) 2026 ZylxEmu Emulator Project
SPDX-License-Identifier: GPL-2.0-or-later
-->

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ZylxEmu.ShaderCompiler\ZylxEmu.ShaderCompiler.csproj" />
    <ProjectReference Include="..\..\src\ZylxEmu.ShaderCompiler.Vulkan\ZylxEmu.ShaderCompiler.Vulkan.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
</Project>
